version: '2'
services:
  php5.6-apache-mysql:
    build: ./
    volumes:
      - ./www:/var/www/html/
    ports:
      - "8888:80"
    links:
      - mysql

  mysql:
    build: ./mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
