version: '2'
services:
  php7.2-extension-debug:
    build: ./
    volumes:
      - ./extension:/extension/
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "8888:80"