version: '2'
services:
  php7.2-fpm-debug:
    build: ./
    volumes:
      - ./www:/var/www/html/
    ports:
      - "80:80"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
